apiVersion: v1
kind: Service
metadata:
  name: chartserver-service
  namespace: chartserver-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{ if .Values.service.https.enabled }}
    - name: https
      port: {{ .Values.service.https.port }}
      targetPort: https
      {{ end }}
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
