project_name: chartserver
release:
  github:
    owner: chartserver
    name: chartserver
builds:
  - id: chartserver
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/manager/main.go
    ldflags: -s -w
      -X github.com/chartserver/chartserver/pkg/version.version={{.Version}}
      -X github.com/chartserver/chartserver/pkg/version.gitSHA={{.Commit}}
      -X github.com/chartserver/chartserver/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: manager
    hooks: {}
archives:
  - id: tar
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}-alpha'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
dockers:
  - dockerfile: ./deploy/Dockerfile.manager
    image_templates:
      - "chartserver/chartserver-manager:alpha"
    binaries:
      - manager
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
